before_script:
  - phantomjs --version
  - cat /etc/hosts
  - cat /etc/resolv.conf
rvm:
  - 1.9.3
  # - 1.9.2
  # - 1.8.7
  # - rbx-18mode
  # - rbx-19mode
  # - jruby-18mode
  # - jruby-19mode
gemfile:
  # - Gemfile
  # - ci/Gemfile.capybara1-0
  - ci/Gemfile.capybara1-1
# matrix:
#   allow_failures:
#     - rvm: rbx-18mode
#     - rvm: rbx-19mode
